AWS_ML_URL: http://43.200.197.251:80

AWS_BE_URL: http://localhost:8080

uploadDir: ./img/

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: test

#logging.level:
#  org.hibernate.SQL: debug

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#      format_sql: true
#    show_sql: true

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: false # 운영시 false로 변경
