AWS_ML_URL: http://43.200.197.251:80
AWS_BE_URL: http://43.200.91.200:8080

uploadDir: ./img/

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true
    show_sql: true

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true # 운영시 false로 변경
