AWS_ML_URL: http://43.200.197.251:80
AWS_BE_URL: http://43.200.91.200:8080

uploadDir: ../img/

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/soma?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 3325
    driverClassName: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:mariadb://voyager-database.cluster-cj29ypjyztnq.ap-northeast-2.rds.amazonaws.com:3306/voyager
#    username: admin
#    password: wndnjs123
#    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      format_sql: true
    show_sql: true

logging.level:
  org.hibernate.SQL: INFO

#logging:
#  config: classpath:logback-spring-prod.xml

decorator:
  datasource:
    p6spy:
      enable-logging: false